services:
  guardrails-ui:
    image: guardrail-ui
    container_name: guardrails-ui
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    depends_on:
      - guardrails-demo

  guardrails-demo:
    image: guardrails-demo:latest
    container_name: guardrails-demo
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - guardrails_cache:/root/.cache
    stdin_open: true
    tty: true

volumes:
  guardrails_cache:
